### ISSUE TITLE
git:// protocol is deprecated by GitHub

### ISSUE THREAD

**Issue by yurikoles** [chaotic-aur/pkgbuild-intel-ucode-git#1]
Clone is failing with error:

```
  The unauthenticated git protocol on port 9418 is no longer supported.
Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.
error: could not fetch origin
```

**Comment by yurikoles** [comment]
Please deploy this change to AUR.

**Comment by dr460nf1r3** [comment]
Hey, sorry I forgot about that! Will be able to push it at the weekend :)

**Comment by PedroHLC** [comment]
@yurikoles but the last commit dcb8a05 is also the one in AUR...

**EDIT**: Damnn, I pushed it yesterday and forgot...
